PAPERMILL: true
RNG_SEED: 1
JAX_PLATFORM: tpu
ALGORITHM: wolff
DIMENSIONS: 2
SPIN: 0.5
TOTAL_SAMPLES: 256
N_TEMPS: 64
N_SAMPLES_VECTORISE: 4
THERMALISE_STEPS: 100
THERMALISE_SWEEPS_PER_STEP: 100
TEMP_MIN: 0.8
TEMP_MAX: 1.5
